
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/nix/store/hkbylipx1iiawqdcjv858p501wv81bpm-bash-interactive-5.3p3/bin/"
      - "/nix/store/r9wbjib6xxjkyb9yvjvrkl4sq61i2lyn-gcc-wrapper-15.2.0/bin/"
      - "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/bin/"
      - "/nix/store/7ri1mm5y99nkr7657r77wycrvhg7z9x0-glibc-2.40-66-bin/bin/"
      - "/nix/store/d75200gb22v7p0703h5jrkgg8bqydk5q-coreutils-9.8/bin/"
      - "/nix/store/dwiyp91lmxq864plaas14jm14m87sg3f-binutils-wrapper-2.44/bin/"
      - "/nix/store/cl88v2m1y5q3k6jlkq5jjf73nmfgl1px-binutils-2.44/bin/"
      - "/nix/store/n5m6p0j4anvf5cyy79nb2qn7smkzs176-gnumake-4.4.1/bin/"
      - "/nix/store/hxn2qrz1zmk5q01wsb7n3d58brzrsizb-pkg-config-wrapper-0.29.2/bin/"
      - "/nix/store/cp6ybr8hv8hqk91l1hp366p40f313gl7-glew-2.2.0-bin/bin/"
      - "/nix/store/95a688lk14i0y5y70fwh9qhjd84490yd-clang-tools-21.1.7/bin/"
      - "/nix/store/gf8lrci4n2hbman2i7pcc7jqnz8l0dgs-bear-3.1.6/bin/"
      - "/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin/"
      - "/nix/store/3vs2fr2mazafcdwyza15bfhpmccx1k7z-patchelf-0.15.2/bin/"
      - "/nix/store/wd99g2j010fdkry0ws1bhxzm52w82ssx-findutils-4.10.0/bin/"
      - "/nix/store/20zvyjvxq9x2mkp7rbnvrwjjzq2n76hh-diffutils-3.12/bin/"
      - "/nix/store/k06ssckzrzn9jjvvs4n62m6567zmbx6x-gnused-4.9/bin/"
      - "/nix/store/qfmq7p42ak5yn389qvx7zpxkan5i4xiy-gnugrep-3.12/bin/"
      - "/nix/store/nmxm04dhkaqg1q6hai70n9zmzb0q49a5-gawk-5.3.2/bin/"
      - "/nix/store/k1lcfin159706lihwx5hhvl80dbij4jw-gnutar-1.35/bin/"
      - "/nix/store/0hv4z5s3r1h4lmvn0427mlxjxgvg34nr-gzip-1.14/bin/"
      - "/nix/store/p61ba9fdgx3358bpp18hv4rslf6n5bq6-bzip2-1.0.8-bin/bin/"
      - "/nix/store/mkm3my2067305hdh7rzmi10npwr7y17f-gnumake-4.4.1/bin/"
      - "/nix/store/lw117lsr8d585xs63kx5k233impyrq7q-bash-5.3p3/bin/"
      - "/nix/store/clrf4mjwr8xcfpvway6w34wzvqc1hry4-patch-2.8/bin/"
      - "/nix/store/j1zc5jh0vi9sbxj09ldj4xklgm6kpf8n-xz-5.8.1-bin/bin/"
      - "/nix/store/s2k48fw3y698j4kcvmw0520m06ihv2z4-file-5.45/bin/"
      - "/run/wrappers/bin/"
      - "/home/nils/.local/share/flatpak/exports/bin/"
      - "/var/lib/flatpak/exports/bin/"
      - "/home/nils/.nix-profile/bin/"
      - "/nix/profile/bin/"
      - "/home/nils/.local/state/nix/profile/bin/"
      - "/etc/profiles/per-user/nils/bin/"
      - "/nix/var/nix/profiles/default/bin/"
      - "/run/current-system/sw/bin/"
      - "/nix/store/ipyljbrgwrcz8jcw1i67q87izgc18ga6-hyprland-qtutils-0.1.5/bin/"
      - "/nix/store/lmmdafjmcb0prbai0x08s6fij30r74bh-pciutils-3.14.0/bin/"
      - "/nix/store/hszr65lapmbkwvb7sdx68nv18dpq16jf-pkgconf-wrapper-2.4.3/bin/"
    searched_directories:
      - "/nix/store/hkbylipx1iiawqdcjv858p501wv81bpm-bash-interactive-5.3p3/bin/uname"
      - "/nix/store/r9wbjib6xxjkyb9yvjvrkl4sq61i2lyn-gcc-wrapper-15.2.0/bin/uname"
      - "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/bin/uname"
      - "/nix/store/7ri1mm5y99nkr7657r77wycrvhg7z9x0-glibc-2.40-66-bin/bin/uname"
    found: "/nix/store/d75200gb22v7p0703h5jrkgg8bqydk5q-coreutils-9.8/bin/uname"
    search_context:
      ENV{PATH}:
        - "/nix/store/hkbylipx1iiawqdcjv858p501wv81bpm-bash-interactive-5.3p3/bin"
        - "/nix/store/r9wbjib6xxjkyb9yvjvrkl4sq61i2lyn-gcc-wrapper-15.2.0/bin"
        - "/nix/store/qarrb8yfby1yyypm32vabzgxgq3w41ma-gcc-15.2.0/bin"
        - "/nix/store/7ri1mm5y99nkr7657r77wycrvhg7z9x0-glibc-2.40-66-bin/bin"
        - "/nix/store/d75200gb22v7p0703h5jrkgg8bqydk5q-coreutils-9.8/bin"
        - "/nix/store/dwiyp91lmxq864plaas14jm14m87sg3f-binutils-wrapper-2.44/bin"
        - "/nix/store/cl88v2m1y5q3k6jlkq5jjf73nmfgl1px-binutils-2.44/bin"
        - "/nix/store/n5m6p0j4anvf5cyy79nb2qn7smkzs176-gnumake-4.4.1/bin"
        - "/nix/store/hxn2qrz1zmk5q01wsb7n3d58brzrsizb-pkg-config-wrapper-0.29.2/bin"
        - "/nix/store/cp6ybr8hv8hqk91l1hp366p40f313gl7-glew-2.2.0-bin/bin"
        - "/nix/store/95a688lk14i0y5y70fwh9qhjd84490yd-clang-tools-21.1.7/bin"
        - "/nix/store/gf8lrci4n2hbman2i7pcc7jqnz8l0dgs-bear-3.1.6/bin"
        - "/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/bin"
        - "/nix/store/3vs2fr2mazafcdwyza15bfhpmccx1k7z-patchelf-0.15.2/bin"
        - "/nix/store/d75200gb22v7p0703h5jrkgg8bqydk5q-coreutils-9.8/bin"
        - "/nix/store/wd99g2j010fdkry0ws1bhxzm52w82ssx-findutils-4.10.0/bin"
        - "/nix/store/20zvyjvxq9x2mkp7rbnvrwjjzq2n76hh-diffutils-3.12/bin"
        - "/nix/store/k06ssckzrzn9jjvvs4n62m6567zmbx6x-gnused-4.9/bin"
        - "/nix/store/qfmq7p42ak5yn389qvx7zpxkan5i4xiy-gnugrep-3.12/bin"
        - "/nix/store/nmxm04dhkaqg1q6hai70n9zmzb0q49a5-gawk-5.3.2/bin"
        - "/nix/store/k1lcfin159706lihwx5hhvl80dbij4jw-gnutar-1.35/bin"
        - "/nix/store/0hv4z5s3r1h4lmvn0427mlxjxgvg34nr-gzip-1.14/bin"
        - "/nix/store/p61ba9fdgx3358bpp18hv4rslf6n5bq6-bzip2-1.0.8-bin/bin"
        - "/nix/store/mkm3my2067305hdh7rzmi10npwr7y17f-gnumake-4.4.1/bin"
        - "/nix/store/lw117lsr8d585xs63kx5k233impyrq7q-bash-5.3p3/bin"
        - "/nix/store/clrf4mjwr8xcfpvway6w34wzvqc1hry4-patch-2.8/bin"
        - "/nix/store/j1zc5jh0vi9sbxj09ldj4xklgm6kpf8n-xz-5.8.1-bin/bin"
        - "/nix/store/s2k48fw3y698j4kcvmw0520m06ihv2z4-file-5.45/bin"
        - "/run/wrappers/bin"
        - "/home/nils/.local/share/flatpak/exports/bin"
        - "/var/lib/flatpak/exports/bin"
        - "/home/nils/.nix-profile/bin"
        - "/nix/profile/bin"
        - "/home/nils/.local/state/nix/profile/bin"
        - "/etc/profiles/per-user/nils/bin"
        - "/nix/var/nix/profiles/default/bin"
        - "/run/current-system/sw/bin"
        - "/nix/store/dwiyp91lmxq864plaas14jm14m87sg3f-binutils-wrapper-2.44/bin"
        - "/nix/store/ipyljbrgwrcz8jcw1i67q87izgc18ga6-hyprland-qtutils-0.1.5/bin"
        - "/nix/store/lmmdafjmcb0prbai0x08s6fij30r74bh-pciutils-3.14.0/bin"
        - "/nix/store/hszr65lapmbkwvb7sdx68nv18dpq16jf-pkgconf-wrapper-2.4.3/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/wmb16s8hw1vd25vvidwnncpzq126lcz3-cmake-4.1.2/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.12.63 - x86_64
...
